export const MAPPED_LABELS = {
  logo: 'Squares Game',
  resumeGame: 'Resume game',
  startGame: 'Start new game',
  playAgain: 'Play again',
  settings: 'Settings',
  instructions: 'Instructions',
  goBack: 'Go back',
  menu: 'Menu',
  save: 'Save',
  cancel: 'Cancel',
  chooseBoardSize: 'Choose the board size',
  boardSize: 'Board size',
  colorScheme: 'Color scheme',
  x3: 'Small (3x3)',
  x4: 'Medium (4x4)',
  x6: 'Large (6x6)',
  x8: 'Extra Large (8x8)',
  instructionsPageContent:
    'Squares is a simple two player game where a square shaped game board is split to N*N squares. (2 ≤ N ≤ 8) Each player marks a square on their turn and at the end, the player with the biggest directly connecting squares group wins.',
  score: 'Score',
  draw: 'Draw!',
  youScoredTheSame: 'You both scored the same',
  congratulations: 'Congratulations',
  won: 'won',
};
